name: Deploy

on:
  push:
    branches:
      - aws-hosting

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CLIENT_EMAIL: ${{ vars.CLIENT_EMAIL }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          NEXT_PUBLIC_SEARCH_ALGOLIA_KEY: ${{ secrets.NEXT_PUBLIC_SEARCH_ALGOLIA_KEY }}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          npx sst deploy --stage prod
